apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: alpine
    image: alpine:latest
    securityContext:
      privileged: true
      runAsUser: 0
---
apiVersion: v1
kind: Pod
metadata:
  name: safe-pod
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
