import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { motion, useReducedMotion } from 'framer-motion'
import {
  Shield,
  ShieldAlert,
  Network,
  Lock,
  ArrowRight,
  Database,
  Flame,
  CheckCircle2,
  Sliders,
  Sparkles,
  Layers,
  Terminal,
  RefreshCw,
  FileCheck2,
  Cpu,
} from 'lucide-react'

import '../landing.css'
import ScrollProgressBar from '../components/common/ScrollProgressBar'
import BackToTop from '../components/common/BackToTop'
import FeedbackModal from '../components/common/FeedbackModal'
import Navbar from '../components/landing/Navbar'
import SecuritySection from '../components/landing/SecuritySection'
import Footer from '../components/landing/Footer'

export default function Security() {
  const [feedbackOpen, setFeedbackOpen] = useState(false)
  const prefersReduced = useReducedMotion()

  const [theme, setTheme] = useState(() => {
    try {
      const saved = localStorage.getItem('agentshield-theme')
      if (saved === 'dark' || saved === 'light') return saved
    } catch {
      // fallback
    }
    return 'dark'
  })

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
    document.body.setAttribute('data-theme', theme)
    document.documentElement.className = theme
    document.body.className = theme
    try {
      localStorage.setItem('agentshield-theme', theme)
    } catch {
      // fallback
    }
  }, [theme])

  useEffect(() => {
    window.scrollTo(0, 0)
  }, [])

  const securitySafeguards = [
    {
      title: 'Composite Risk Prioritization Engine',
      category: 'Mathematical Triage',
      icon: Sliders,
      tag: 'Triage Formula',
      metric: '0–100 Unified Score',
      desc: 'Replaces noisy raw linter counts with a unified priority score combining base CVSS severity (50%), topological exposure (30%), and downstream blast radius (20%), calibrated by dual-LLM ensemble confidence.',
      formula: 'Priority = (0.5*S + 0.3*E + 0.2*B) * (0.5 + 0.5*C)',
      highlights: [
        'Eliminates developer alert fatigue',
        'Topological exposure weighted from perimeter ingress',
        'Multi-LLM confidence suppresses false alarms',
      ],
    },
    {
      title: 'Zero-Leakage Secret Interception',
      category: 'Perimeter Defense',
      icon: Lock,
      tag: 'Cryptographic Masking',
      metric: '0 Tokens Sent to LLMs',
      desc: 'Integrates Gitleaks, TruffleHog, and Shannon entropy heuristics to detect cleartext AWS keys, private certificates, and tokens. Credentials are cryptographically masked locally before prompt transmission.',
      formula: 'Local Redaction: s/AKIA[0-9A-Z]{16}/[REDACTED_AWS_KEY]/g',
      highlights: [
        'Shannon entropy scanning (> 4.5 threshold)',
        'Zero credential leakage to external LLM endpoints',
        'Preserves AST code structure for safe parsing',
      ],
    },
    {
      title: 'Live Cloud Drift Detection & Reconciliation',
      category: 'Runtime Governance',
      icon: RefreshCw,
      tag: 'Multi-Cloud Drift Engine',
      metric: 'Read-Only Cloud Auditing',
      desc: 'Audits live cloud infrastructure state (AWS, Azure, GCP) against declared AST configurations without mutating live assets. Detects out-of-band security group mutations, S3 ACL degradation, and unmanaged resources.',
      formula: 'DriftClassification: ADDED | DELETED | MODIFIED',
      highlights: [
        'Read-only cloud queries (AWS EC2/S3/IAM, Azure NSG, GCP Firewall)',
        'Synthesizes unified reconciliation diffs',
        'Integrates with Shift-Left pre-commit protection',
      ],
    },
    {
      title: 'Two-Tier Sandbox Validation Harness',
      category: 'Patch Integrity',
      icon: FileCheck2,
      tag: 'LocalStack Emulation',
      metric: '100% Patch Syntax Validity',
      desc: 'Every automated patch generated by the Remediation Agent passes through static linters (terraform validate, cfn-lint, kube-linter) followed by containerized dry-run deployment inside LocalStack to verify provisioning integrity.',
      formula: 'Gate: LinterPass && LocalStackDryRun -> AuthorizedMerge',
      highlights: [
        'Zero runtime regression guarantee',
        'Automated rollback if validation fails',
        'Produces clean, git-mergeable unified diffs',
      ],
    },
  ]

  const complianceFrameworks = [
    {
      name: 'CIS Benchmarks',
      desc: 'Hardening benchmarks for AWS Foundations, Microsoft Azure, and Kubernetes v1.28.',
      controls: ['CIS AWS 2.1.5', 'CIS Azure 3.1', 'CIS K8s 5.2.2'],
    },
    {
      name: 'NIST SP 800-53 Rev. 5',
      desc: 'Security and Privacy Controls for Federal Information Systems and Organizations.',
      controls: ['AC-6 Least Privilege', 'SC-7 Boundary Protection', 'IA-2 Identification'],
    },
    {
      name: 'SOC 2 Type II',
      desc: 'Trust Services Criteria for Security, Availability, and Confidentiality.',
      controls: ['CC6.1 Logical Access', 'CC6.3 Access Modification', 'CC6.8 Threat Defense'],
    },
    {
      name: 'PCI-DSS v4.0',
      desc: 'Payment Card Industry Data Security Standard for cardholder data environments.',
      controls: ['Req 1.3 Ingress Filtering', 'Req 2.2 System Standards', 'Req 7.1 Access Control'],
    },
    {
      name: 'HIPAA Security Rule',
      desc: 'Technical safeguards for Electronic Protected Health Information (ePHI).',
      controls: ['45 CFR § 164.312(a)(1)', '45 CFR § 164.312(e)(1) Encryption'],
    },
  ]

  return (
    <div className={`agentshield-landing-root ${theme}`} data-theme={theme}>
      {/* Visual Reading / Scroll Progress Bar */}
      <ScrollProgressBar />

      {/* Global Navigation Bar */}
      <Navbar theme={theme} setTheme={setTheme} activeRoute="security" />

      {/* Main Page Content */}
      <main className="landing-main-flow">
        {/* Dedicated Security Page Hero */}
        <section className="dedicated-hero-section" aria-label="Security Introduction">
          <div className="section-container">
            <div className="dedicated-hero-content text-center">
              <motion.div
                className="section-eyebrow-wrapper"
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
              >
                <span className="section-eyebrow">
                  <span className="eyebrow-accent-dot" />
                  DEEP DIVE: CONTEXTUAL TOPOLOGY &amp; RISK
                </span>
              </motion.div>

              <motion.h1
                className="dedicated-hero-heading"
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.1 }}
              >
                SECURITY THAT THINKS IN
                <br />
                <span className="heading-gradient">EXPLOIT PATHS.</span>
              </motion.h1>

              <motion.p
                className="dedicated-hero-subheading"
                initial={{ opacity: 0, y: 14 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.2 }}
              >
                Traditional security scanners inspect code line by line, generating hundreds of
                unranked warnings. AgentShield-AI builds topological dependency graphs from
                Infrastructure-as-Code to reveal attack routes, isolate choke points, and remediate
                root vulnerabilities before deployment.
              </motion.p>

              {/* Jump Navigation Pills */}
              <motion.div
                className="dedicated-jump-nav"
                initial={{ opacity: 0, y: 14 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: 0.3 }}
              >
                <a href="#security" className="jump-nav-pill">
                  <span className="jump-nav-num">01</span>
                  <span>Attack-Path Intelligence</span>
                </a>
                <a href="#safeguards" className="jump-nav-pill">
                  <span className="jump-nav-num">02</span>
                  <span>Defense Safeguards</span>
                </a>
                <a href="#compliance" className="jump-nav-pill">
                  <span className="jump-nav-num">03</span>
                  <span>Compliance Matrix</span>
                </a>
              </motion.div>
            </div>
          </div>
        </section>

        {/* 1. Interactive Contextual Topology & Attack Path Scenario Explorer */}
        <SecuritySection />

        {/* 2. Deep-Dive Security Safeguards Grid */}
        <section className="security-safeguards-section" id="safeguards" aria-label="Security Safeguards">
          <div className="section-container">
            <div className="section-header-block text-center">
              <span className="section-eyebrow">
                <span className="eyebrow-accent-dot" />
                FOUNDATIONAL DEFENSE ENGINES
              </span>
              <h2 className="section-main-heading">
                MATHEMATICAL RIGOR &amp;
                <br />
                <span className="heading-gradient">ZERO-LEAKAGE DEFENSE.</span>
              </h2>
              <p className="section-subheading">
                How AgentShield eliminates false alarms, shields developer credentials, and ensures
                remediation patches are mathematically sound and syntactically validated.
              </p>
            </div>

            <div className="safeguards-cards-grid">
              {securitySafeguards.map((item) => {
                const IconComponent = item.icon
                return (
                  <div key={item.title} className="safeguard-card">
                    <div className="safeguard-card-header">
                      <div className="safeguard-icon-box">
                        <IconComponent size={20} />
                      </div>
                      <div className="safeguard-tags">
                        <span className="safeguard-tag">{item.tag}</span>
                        <span className="safeguard-metric">{item.metric}</span>
                      </div>
                    </div>

                    <span className="safeguard-category">{item.category}</span>
                    <h3 className="safeguard-title">{item.title}</h3>
                    <p className="safeguard-desc">{item.desc}</p>

                    <div className="safeguard-formula-box">
                      <span className="formula-label">OPERATIONAL RULE</span>
                      <code>{item.formula}</code>
                    </div>

                    <ul className="safeguard-highlights">
                      {item.highlights.map((hl) => (
                        <li key={hl}>
                          <CheckCircle2 size={13} className="hl-check" />
                          <span>{hl}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )
              })}
            </div>
          </div>
        </section>

        {/* 3. Automated Compliance Mappings Matrix */}
        <section className="compliance-matrix-section" id="compliance" aria-label="Compliance Standards">
          <div className="section-container">
            <div className="section-header-block text-center">
              <span className="section-eyebrow">
                <span className="eyebrow-accent-dot" />
                GOVERNANCE &amp; STANDARDS
              </span>
              <h2 className="section-main-heading">
                MAPPED COMPLIANCE
                <br />
                <span className="heading-gradient">CONTROLS.</span>
              </h2>
              <p className="section-subheading">
                Every detected IaC finding is automatically correlated with relevant controls across
                major industry regulatory standards.
              </p>
            </div>

            <div className="compliance-cards-grid">
              {complianceFrameworks.map((fw) => (
                <div key={fw.name} className="compliance-card">
                  <div className="compliance-card-header">
                    <Shield size={18} className="compliance-icon" />
                    <h3 className="compliance-name">{fw.name}</h3>
                  </div>
                  <p className="compliance-desc">{fw.desc}</p>
                  <div className="compliance-controls-list">
                    {fw.controls.map((ctrl) => (
                      <span key={ctrl} className="compliance-control-badge">
                        {ctrl}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* 4. Cross-Platform Bridge Section to Architecture & Console */}
        <section className="architecture-bridge-section" aria-label="Explore Related Capabilities">
          <div className="section-container">
            <div className="bridge-cards-grid">
              <div className="bridge-card bridge-card-architecture">
                <div className="bridge-card-icon-box architecture-icon-box">
                  <Cpu size={24} />
                </div>
                <span className="bridge-card-tag">SYSTEM ARCHITECTURE</span>
                <h3 className="bridge-card-title">Explore Platform Architecture</h3>
                <p className="bridge-card-desc">
                  Inspect the 6-agent autonomous pipeline, AST normalization across 4 polyglot
                  frameworks, and Platt-calibrated dual-LLM consensus voting.
                </p>
                <Link to="/architecture" className="bridge-card-cta">
                  <span>Explore Architecture Page</span>
                  <ArrowRight size={15} />
                </Link>
              </div>

              <div className="bridge-card bridge-card-console">
                <div className="bridge-card-icon-box console-icon-box">
                  <Terminal size={24} />
                </div>
                <span className="bridge-card-tag">INTERACTIVE SOC</span>
                <h3 className="bridge-card-title">Audit Your Templates Live</h3>
                <p className="bridge-card-desc">
                  Upload Terraform, CloudFormation, or Kubernetes templates into the AgentShield
                  interactive console for instant attack-path and vulnerability discovery.
                </p>
                <Link to="/scan" className="bridge-card-cta console-cta">
                  <span>Start Interactive Scan</span>
                  <ArrowRight size={15} />
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Comprehensive Footer */}
      <Footer onOpenFeedback={() => setFeedbackOpen(true)} />

      {/* Accessible Back to Top Floating Button */}
      <BackToTop />

      {/* In-App Security / Feedback Modal */}
      <FeedbackModal isOpen={feedbackOpen} onClose={() => setFeedbackOpen(false)} />
    </div>
  )
}
