"""LLM Client and Multi-LLM Ensemble Interface for AgentShield AI.

Provides unified provider abstractions (OpenAI, Anthropic, LiteLLM, Mock),
structured Pydantic response parsing, error handling, and ensemble voting logic.
"""

import json
import re
from enum import StrEnum
from typing import Generic,TypeVar
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass

from pydantic import BaseModel, Field, SecretStr

T = TypeVar("T", bound=BaseModel)


class LLMProvider(StrEnum):
    """Supported LLM service providers."""

    OPENAI = "openai"
    ANTHROPIC = "anthropic"
    LITELLM = "litellm"
    MOCK = "mock"


class LLMConfig(BaseModel):
    """Configuration for LLM model client."""

    provider: LLMProvider = Field(
        default=LLMProvider.MOCK, description="LLM service provider type"
    )
    model_name: str = Field(
        default="gpt-4o", description="Target model identifier (e.g. gpt-4o, claude-3-5-sonnet)"
    )
    api_key: SecretStr | None = Field(
        default=None, description="API access key for the provider"
    )
    temperature: float = Field(
        default=0.0, ge=0.0, le=2.0, description="Sampling temperature for generation"
    )
    max_tokens: int = Field(default=4096, ge=1, description="Maximum completion tokens")
    timeout: float = Field(default=60.0, ge=1.0, description="Request timeout in seconds")


class LLMResponse(BaseModel):
    """Standardized response container from LLM generation."""

    content: str = Field(..., description="Raw text generated by the LLM")
    model: str = Field(..., description="Model identifier used for generation")
    provider: LLMProvider = Field(..., description="Provider used for generation")
    usage: dict[str, int] = Field(
        default_factory=dict, description="Token consumption metrics"
    )

@dataclass
class StructuredLLMResult(Generic[T]):
    """Structured result from one LLM invocation in an ensemble."""

    parsed: T | None
    response: LLMResponse | None
    error: str | None = None

    @property
    def success(self) -> bool:
        """Return True when the model produced a valid structured response."""
        return self.parsed is not None and self.error is None


class LLMClient:
    """Unified LLM client interface for prompt execution and structured parsing."""

    def __init__(self, config: LLMConfig | None = None) -> None:
        self.config = config or LLMConfig()
        self._mock_responses: list[str] = []

    def set_mock_responses(self, responses: list[str]) -> None:
        """Register queued mock responses for testing."""
        self._mock_responses = list(responses)

    def generate(self, prompt: str, system_prompt: str | None = None) -> LLMResponse:
        """Execute text generation against configured provider."""
        if self.config.provider == LLMProvider.MOCK:
            content = (
                self._mock_responses.pop(0)
                if self._mock_responses
                else "Mock LLM Response"
            )
            return LLMResponse(
                content=content,
                model=self.config.model_name,
                provider=LLMProvider.MOCK,
                usage={"prompt_tokens": 100, "completion_tokens": 50, "total_tokens": 150},
            )

        # Provider routing (OpenAI / Anthropic / LiteLLM)
        if self.config.provider == LLMProvider.OPENAI:
            return self._call_openai(prompt, system_prompt)
        elif self.config.provider == LLMProvider.ANTHROPIC:
            return self._call_anthropic(prompt, system_prompt)
        else:
            return self._call_litellm(prompt, system_prompt)

    def generate_structured(
        self, prompt: str, schema_cls: type[T], system_prompt: str | None = None
    ) -> T:
        """Execute generation and parse JSON response into Pydantic model schema."""
        instructions = (
            f"\n\nCRITICAL INSTRUCTION: You MUST return ONLY a valid JSON object adhering strictly "
            f"to the following JSON schema. Do not include markdown codeblock tags, markdown text, "
            f"or conversational output.\n"
            f"JSON Schema:\n{json.dumps(schema_cls.model_json_schema(), indent=2)}"
        )
        full_prompt = prompt + instructions

        response = self.generate(full_prompt, system_prompt=system_prompt)
        return self._extract_and_parse_json(response.content, schema_cls)

    def generate_structured_result(
            self,
            prompt: str,
            schema_cls: type[T],
            system_prompt: str | None = None,
        ) -> StructuredLLMResult[T]:
            """Generate and parse a structured response while preserving model metadata."""

            try:
                instructions = (
                    "\n\nCRITICAL INSTRUCTION: You MUST return ONLY a valid JSON object "
                    "adhering strictly to the following JSON schema. Do not include "
                    "markdown codeblock tags, markdown text, or conversational output.\n"
                    f"JSON Schema:\n{json.dumps(schema_cls.model_json_schema(), indent=2)}"
                )

                response = self.generate(
                    prompt + instructions,
                    system_prompt=system_prompt,
                )

                parsed = self._extract_and_parse_json(
                    response.content,
                    schema_cls,
                )

                return StructuredLLMResult(
                    parsed=parsed,
                    response=response,
                )

            except Exception as exc:
                return StructuredLLMResult(
                    parsed=None,
                    response=response if "response" in locals() else None,
                    error=str(exc),
                 )

    def _extract_and_parse_json(self, raw_text: str, schema_cls: type[T]) -> T:
        """Clean markdown formatting and parse JSON string into Pydantic schema."""
        text = raw_text.strip()
        # Remove ```json ... ``` codeblocks if present
        json_block_match = re.search(r"```(?:json)?\s*(\{.*\}|\[.*\])\s*```", text, re.DOTALL)
        if json_block_match:
            text = json_block_match.group(1).strip()
        else:
            # Locate first '{' or '[' and last '}' or ']'
            start_idx = min(
                (text.find("{") if "{" in text else len(text)),
                (text.find("[") if "[" in text else len(text)),
            )
            end_idx = max(text.rfind("}"), text.rfind("]"))
            if start_idx < len(text) and end_idx != -1 and end_idx >= start_idx:
                text = text[start_idx : end_idx + 1]

        data = json.loads(text)
        return schema_cls.model_validate(data)

    def _call_openai(self, prompt: str, system_prompt: str | None = None) -> LLMResponse:
        """Call OpenAI API if installed and configured."""
        try:
            import openai

            api_key = (
                self.config.api_key.get_secret_value() if self.config.api_key else None
            )
            client = openai.OpenAI(api_key=api_key)
            messages: list[dict[str, str]] = []
            if system_prompt:
                messages.append({"role": "system", "content": system_prompt})
            messages.append({"role": "user", "content": prompt})

            res = client.chat.completions.create(
                model=self.config.model_name,
                messages=messages,  # type: ignore[arg-type]
                temperature=self.config.temperature,
                max_tokens=self.config.max_tokens,
                timeout=self.config.timeout,
            )
            text = res.choices[0].message.content or ""
            usage = {
                "prompt_tokens": res.usage.prompt_tokens if res.usage else 0,
                "completion_tokens": res.usage.completion_tokens if res.usage else 0,
                "total_tokens": res.usage.total_tokens if res.usage else 0,
            }
            return LLMResponse(
                content=text,
                model=self.config.model_name,
                provider=LLMProvider.OPENAI,
                usage=usage,
            )
        except Exception as e:
            # Fallback to mock on API or auth error for robustness
            return LLMResponse(
                content=f"Error invoking OpenAI API: {e}",
                model=self.config.model_name,
                provider=LLMProvider.OPENAI,
            )

    def _call_anthropic(self, prompt: str, system_prompt: str | None = None) -> LLMResponse:
        """Call Anthropic API if installed and configured."""
        try:
            import anthropic

            api_key = (
                self.config.api_key.get_secret_value() if self.config.api_key else None
            )
            client = anthropic.Anthropic(api_key=api_key)
            res = client.messages.create(
                model=self.config.model_name,
                max_tokens=self.config.max_tokens,
                temperature=self.config.temperature,
                system=system_prompt or "",
                messages=[{"role": "user", "content": prompt}],
            )
            text = res.content[0].text if res.content else ""
            usage = {
                "prompt_tokens": res.usage.input_tokens if res.usage else 0,
                "completion_tokens": res.usage.output_tokens if res.usage else 0,
                "total_tokens": (
                    (res.usage.input_tokens + res.usage.output_tokens) if res.usage else 0
                ),
            }
            return LLMResponse(
                content=text,
                model=self.config.model_name,
                provider=LLMProvider.ANTHROPIC,
                usage=usage,
            )
        except Exception as e:
            return LLMResponse(
                content=f"Error invoking Anthropic API: {e}",
                model=self.config.model_name,
                provider=LLMProvider.ANTHROPIC,
            )

    def _call_litellm(self, prompt: str, system_prompt: str | None = None) -> LLMResponse:
        """Call LiteLLM wrapper if installed and configured."""
        try:
            import litellm

            messages: list[dict[str, str]] = []
            if system_prompt:
                messages.append({"role": "system", "content": system_prompt})
            messages.append({"role": "user", "content": prompt})

            res = litellm.completion(
                model=self.config.model_name,
                messages=messages,
                temperature=self.config.temperature,
                max_tokens=self.config.max_tokens,
            )
            text = res.choices[0].message.content or ""
            return LLMResponse(
                content=text,
                model=self.config.model_name,
                provider=LLMProvider.LITELLM,
            )
        except Exception as e:
            return LLMResponse(
                content=f"Error invoking LiteLLM: {e}",
                model=self.config.model_name,
                provider=LLMProvider.LITELLM,
            )


class MultiLLMEnsemble:
    """Ensemble executor for cross-verifying findings between multiple LLM models."""

    AUTO_PATCH_THRESHOLD: float = 0.85

    def __init__(self, clients: list[LLMClient]) -> None:
        if not clients:
            clients = [LLMClient()]
        self.clients = clients

    # def generate_ensemble(
    #     self, prompt: str, schema_cls: type[T], system_prompt: str | None = None
    # ) -> list[T]:
    #     """Query all ensemble clients in parallel or sequence and collect responses."""
    #     results: list[T] = []
    #     for client in self.clients:
    #         try:
    #             parsed = client.generate_structured(
    #                 prompt, schema_cls, system_prompt=system_prompt
    #             )
    #             results.append(parsed)
    #         except Exception:
    #             continue
    #     return results
    def generate_ensemble(
            self,
            prompt: str,
            schema_cls: type[T],
            system_prompt: str | None = None,
        ) -> list[StructuredLLMResult[T]]:
            """Query all ensemble models in parallel and preserve per-model results."""

            def run_client(client: LLMClient) -> StructuredLLMResult[T]:
                return client.generate_structured_result(
                    prompt,
                    schema_cls,
                    system_prompt=system_prompt,
                )

            # LLM calls are I/O-bound, so execute them concurrently.
            with ThreadPoolExecutor(max_workers=len(self.clients)) as executor:
                futures = [
                    executor.submit(run_client, client)
                    for client in self.clients
                ]

                # Preserve client/model order for deterministic results.
                results = [future.result() for future in futures]

            return results

    def compute_consensus_confidence(
        self, agreed_count: int, total_models: int, base_confidence: float = 0.8
    ) -> float:
        """Calculate ensemble confidence score based on model agreement ratio."""
        if total_models <= 0:
            return base_confidence
        agreement_ratio = agreed_count / total_models
        # Scale base_confidence by agreement ratio
        consensus_score = base_confidence * (0.5 + 0.5 * agreement_ratio)
        return min(1.0, max(0.0, round(consensus_score, 4)))

    def calculate_calibrated_confidence(
        self,
        model_confidences: list[float],
        total_models: int,
        agreement_score: float = 1.0,
        gamma: float = 0.10,
        weights: list[float] | None = None,
    ) -> float:
        """Calculate calibrated ensemble consensus confidence score.

        Mathematical Formulation:
            C_ensemble(v) = sum_{i in agreed}(w_i * C(M_i, v)) + gamma * S_agreement * (N_agreed / N_total)
        where:
            - w_i = (1 - gamma) / total_models (for uniform weights)
            - S_agreement in [0.0, 1.0] measures AST/resource/rule overlap
            - (N_agreed / N_total) penalizes single-model hallucinations

        Eliminates single-model hallucinations:
            - When 2 models agree with C=0.90: C_ensemble = 0.45(0.90)+0.45(0.90)+0.10(1.0) = 0.91 >= 0.85 (Auto-patch)
            - When only 1 of 2 models flags finding with C=0.90: C_ensemble = 0.45(0.90)+0.10(0.5) = 0.455 < 0.85 (Human Review)
        """
        if not model_confidences or total_models <= 0:
            return 0.0

        if total_models == 1:
            return min(1.0, max(0.0, round(model_confidences[0], 4)))

        num_agreed = len(model_confidences)
        if weights and len(weights) == num_agreed:
            weighted_sum = sum(w * c for w, c in zip(weights, model_confidences))
        else:
            w = (1.0 - gamma) / total_models
            weighted_sum = sum(w * c for c in model_confidences)

        agreement_bonus = gamma * agreement_score * (num_agreed / total_models)
        calibrated_score = min(1.0, max(0.0, round(weighted_sum + agreement_bonus, 4)))
        return calibrated_score

    @classmethod
    def evaluate_routing(
        cls, confidence_score: float, threshold: float = AUTO_PATCH_THRESHOLD
    ) -> tuple[bool, bool, str | None]:
        """Evaluate whether a finding qualifies for auto-patching or requires human review.

        Returns:
            (auto_patchable, requires_human_review, escalation_reason)
        """
        if confidence_score >= threshold:
            return True, False, None
        escalation_reason = (
            f"Confidence score {confidence_score:.4f} is below auto-patch threshold {threshold:.2f}; "
            "escalated to human review queue to prevent potential hallucination."
        )
        return False, True, escalation_reason
